### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by antfu** [nuxt/movies#2]
- [x] Rewrite from https://github.com/tastejs/nuxt-movies in Nuxt 3
- [x] 404 Pages and better naivgation @antfu
- [x] Add readme @antfu
- [x] Performance and a11y improvements
- [x] Nuxt Image module

### Discussions

- Should we do some redesign?
- It uses https://github.com/antfu/nuxt-server-fn, what should we do about it?
